### PR TITLE
Syntax error fix

### PR DESCRIPTION
**Pull request by talbergs**

### CODE REVIEW

**Comment by Guria** [comment]
This website is autogenerated from markdown files placed in main repo. You can find 'Edit on github' link on top of each website page to jump right onto corresponded md file.

**Comment by talbergs** [comment]
Yes github but stated "I have no permission to edit in place, so fork will be created"

**Comment by henri-hulski** [comment]
You can make a PR from your fork. 
Github will propose that.

**Comment by Guria** [comment]
Isn't was the same in this repo? :)

**Pull request closed without merging**
